### ISSUE TITLE
Improve memory usage in 2sem/lab1.2/main.cpp

### ISSUE THREAD

**Issue by xLeapProtocol** [VARN0R/BSU_1course_C#1]
Replace str[MAX] and sentence[MAX]
With 
```c
char *str = new char[MAX];
char *sentence = new char[MAX];
```
C++ ISO forbid variable-length array declaration

**Comment by VARN0R** [comment]
I apologize for my inattention.  The code has already been updated in accordance with C++ ISO

Thank you for giving me your time :)
